#!/usr/bin/env bash
install_luajit() {
  if command -v luajit >/dev/null 2>&1; then
    return 0
  fi
  if test -d ./luajit; then
    echo "Using sudo to install LuaJIT"
    cd ./luajit && make && sudo make install \
      || ( echo "ERROR: failed installing LuaJIT" ; cd .. ; exit 1 ) 
    cd ..
  fi
  echo "ERROR: LuaJIT not found"
  return 1
}

install_ygofab() {
  luajit make.lua install || exit 1
}

configure_ygofab() {
  luajit make.lua config "$1" || exit 1
}

install_luajit && install_ygofab && configure_ygofab "$1"
