#!/usr/bin/env bash
install_luajit() {
  if command -v luajit >/dev/null 2>&1; then
    echo "LuaJIT already installed"
    return 0
  fi
  echo "Installing LuaJIT"
  cd "./luajit" && make && sudo make install \
    || ( echo "Failed installing LuaJIT." ; cd .. ; exit 1 ) 
  cd ..
}

install_vips() {
  if command -v luajit >/dev/null 2>&1; then
    echo "libvips already installed"
    return 0
  fi
  echo "Installing libvips"
  cd "./vips" && ./configure && make && sudo make install \
    || ( echo "Failed installing libvips." ; cd .. ; exit 1 )
  cd ..
}

install_ygofab() {
  sudo luajit make.lua install || exit 1
}

configure_ygofab() {
  luajit make.lua config "$1" || exit 1
}

install_fonts() {
  if [[ -d ./fonts ]]; then
    luajit make.lua fonts || exit 1
  fi
}

if [[ $UID != 0 ]]; then
  echo "Please install with sudo."
  exit 1
fi

install_luajit \
  && install_vips \
  && install_ygofab \
  && configure_ygofab "$1" \
  && install_fonts \
  && echo "Go to https://github.com/piface314/ygo-fabrica/wiki to learn how to use! :D"

