#!/bin/bash
echo "Starting YGOFabrica..."
echo "Testing \""$1"\"..."
echo "-------------------------------------"
luajit -l lua-modules.set-paths src/main.lua $@
echo "-------------------------------------"
