#!/bin/bash

declare -A flags
declare -A booleans
args=()

booleans["s"]=false
booleans["v"]=false
booleans["c"]=false

while [ "$1" ];
do
    arg=$1
    if [ "${1:0:1}" == "-" ]
    then
      shift
      rev=$(echo "$arg" | rev)
      if [ -z "$1" ] || [ "${1:0:1}" == "-" ] || [ "${rev:0:1}" == ":" ]
      then
        bool=$(echo ${arg:1} | sed s/://g)
        booleans[$bool]=true
      else
        value=$1
        flags[${arg:1}]=$value
        shift
      fi
    else
      args+=("$arg")
      shift
    fi
done

echo "Starting YGOFabrica..."
luajit -l lua-modules.set-paths src/main.lua ${args[0]} ${args[1]} ${args[2]} ${booleans["s"]} ${booleans["v"]} ${booleans["c"]} ${flags["o"]}
echo "Done!"
