# These are examples of already existing Yu-Gi-Oh! cards described in the format that
#  `ygofab make` uses to transform into `.cdb`.

# You don't have to specify an id to the card, in which case you use [[card]]
[[card]]
id = 41426869
name = "Black Illusion Ritual"
type = "spell ritual"
effect = '''
This card is used to Ritual Summon "Relinquished". You must also Tribute a monster from your hand or field whose Level is 1 or more.'''

[[card]]
id = 80604091
name = "Ultimate Offering"
type = "trap continuous"
effect = '''
During your Main Phase or your opponent's Battle Phase: You can pay 500 Life Points; immediately after this effect resolves, Normal Summon/Set 1 monster.'''

[[card]]
id = 21970285
name = "Dragon Horn Hunter"
attribute = "dark"
level = 6
pendulum-scale = 7 # or [7, 7], so values could be different, like [1, 8]
pendulum-effect = '''
All Normal Monsters gain 200 ATK. You take no battle damage from battles involving Normal Monsters you control.'''
type = "monster normal pendulum"
race = "warrior"
flavor-text = '''
The horns were needed to prepare a medicine for her village, suffering from a plague. Unknown to her, the dragons burned and trampled her village, once displaced from their den.'''
atk = 2300
def = 1000

# Using IDs for cards is completely optional (this might be used in yet unreleased features)
[card.amaterasu]
id = 20073910
name = "Amaterasu"
attribute = "light"
level = 9
type = "monster effect spirit"
race = "fairy"
effect = '''
Cannot be Normal or Special Summoned. During either player's turn, when your opponent activates a card or effect that targets this face-down monster: You can change this card to face-up Defense Position; draw 1 card. If this card is flipped face-up: Banish all other cards on the field. Once per turn, during the End Phase, if this card was flipped face-up this turn: Return it to the hand.'''
atk = 3000
def = 3000

[card.theseus]
id = 96334243
name = "Sea Monster of Theseus"
type = "monster fusion tuner"
attribute = "water"
race = "zombie"
effect = "2 Tuners"
level = 5
atk = 2200
def = 1800

[card.apollousa]
id = 4280258
name = "Apollousa, Bow of the Goddess"
attribute = "wind"
link-arrows = "top bottom-left bottom bottom-right"
type = "monster effect link"
race = "fairy"
effect = '''
2+ monsters with different names, except Tokens
You can only control 1 "Apollousa, Bow of the Goddess". The original ATK of this card becomes 800 x the number of Link Materials used for its Link Summon. Once per Chain, when your opponent activates a monster effect (Quick Effect): You can make this card lose exactly 800 ATK, and if you do, negate the activation.'''
atk = "?"
link-rating = 4
