# These are examples of already existing Yu-Gi-Oh! archetypes described in the format that
#  `ygofab make` uses to transform into `strings.conf`, with some cards using them.

[set.galaxy-eyes]
code = 0x107b
name = "Galaxy-Eyes"

[set.photon]
code = 0x0055
name = "Photon"

[card.paladin]
id = 85346853
name = "Paladin of Photon Dragon"
set = "photon"
attribute = "light"
level = 4
type = "monster effect ritual"
race = "warrior"
effect = '''
You can Ritual Summon this card with "Luminous Dragon Ritual". You can Tribute this card; Special Summon 1 "Galaxy-Eyes Photon Dragon" from your hand or Deck. When this card destroys an opponent's monster by battle and sends it to the Graveyard: Draw 1 card.'''
atk = 1900
def = 800

[card.neo-dragon]
id = 39272762
name = "Neo Galaxy-Eyes Photon Dragon"
set = "galaxy-eyes photon" # two sets, separeted with spaces
attribute = "light"
rank = 8
type = "monster effect xyz"
effect = '''
3 Level 8 monsters
If this card is Xyz Summoned using "Galaxy-Eyes Photon Dragon" as any of its materials: All other face-up cards currently on the field have their effects negated. Once per turn: You can detach 1 material from this card; detach all materials from monsters your opponent controls, then this card gains 500 ATK for each, also it can attack up to that many times during each Battle Phase this turn.'''
atk = 4500
def = 3000

# You can also specify setcodes in the traditional way, using `setcode` instead:
# > Note: duplicate key are forbidden in TOML, this is just an example.
[card.paladin]
setcode = 0x0055

[card.neo-dragon]
setcode = 0x107b0055

# And finally, examples of counters:
[counter.fog]
name = "Fog Counter"
code = 0x1019

[counter.kaiju]
name = "Kaiju Counter"
code = 0x37